### ISSUE TITLE
Remote disconnected without response

### ISSUE THREAD

**Issue by Ian2012** [openedx/event-routing-backends#329]
When using the command `transform_tracking_logs` with S3 as the backend, around 36 minutes in, the following log appears:

```
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/openedx/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 106, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/openedx/requirements/event-routing-backends/event_routing_backends/management/commands/transform_tracking_logs.py", line 267, in handle
    transform_tracking_logs(
  File "/openedx/requirements/event-routing-backends/event_routing_backends/management/commands/transform_tracking_logs.py", line 48, in transform_tracking_logs
    chunks = source.download_object_range_as_stream(
  File "/openedx/venv/lib/python3.8/site-packages/libcloud/storage/drivers/s3.py", line 563, in download_object_range_as_stream
    response = self.connection.request(
  File "/openedx/venv/lib/python3.8/site-packages/libcloud/common/base.py", line 646, in request
    return request_to_be_executed(
  File "/openedx/venv/lib/python3.8/site-packages/libcloud/common/base.py", line 665, in _retryable_request
    self.connection.prepared_request(
  File "/openedx/venv/lib/python3.8/site-packages/libcloud/http.py", line 251, in prepared_request
    self.response = self.session.send(
  File "/openedx/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/openedx/venv/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by bmtcril** [comment]
@Ian2012 Did you only see it once?

**Comment by Ian2012** [comment]
The job dies, so yes
